### ISSUE TITLE
plugin 0.4.4 dependency broken

### ISSUE THREAD

**Issue by elega9t** [mmakowski/specs2-maven-plugin#19]
Hi,

I am getting

The POM for org.scala-lang.modules:scala-parser-combinators_2.11:jar:1.0.0 is missing, no dependency information available

When using the plugin. Can you update the plugin dependency to include a later version please.

Also getting 

java.lang.ClassNotFoundException: org.specs2.runner.TestInterfaceRunner
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.mmakowski.maven.plugins.specs2.Specs2Runner$TestInterfaceRunner.<init>(Specs2Runner.scala:125)
        at com.mmakowski.maven.plugins.specs2.Specs2Runner.runSpecs(Specs2Runner.scala:58)
        at com.mmakowski.maven.plugins.specs2.Specs2RunnerMojo.execute(Specs2RunnerMojo.java:31)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)

**Comment by mmakowski** [comment]
@elega9t: which version of specs2 are you using?

**Comment by elega9t** [comment]
I am using version 3.7

**Comment by mmakowski** [comment]
The plugin does not support 3.x series of specs2 at this point, only 2.x. As I do not actively work on this plugin any more and rely on contributions from community, I cannot give you any timeline on the resolution, I'm afraid.
